#! /usr/bin/env bash

# shellcheck disable=SC2034
LIBRARY_PREFIX="Z__"
OBJECT_PREFIX="OBJ__"

ATTRIBUTES_SUFFIX="__ATTRS"
METHODS_SUFFIX="__METHODS"

OBJECT_TYPE_ATTRIBUTE_NAME="__type__"
OBJECT_PARENT_ATTRIBUTE_NAME="__parent__"
OBJECT_NAME_ATTRIBUTE_NAME="__name__"

CLASS_TYPE_NAME="class"
INSTANCE_TYPE_NAME="instance"

VALID_OBJECT_NAME_REGEX="^[[:alnum:]]+$"
