#! /usr/bin/env bash

# shellcheck disable=SC2034
LIBRARY_PREFIX="Z__"
OBJECT_PREFIX="OBJ__"

BASE_CLASS_NAME="Object"

ATTRIBUTES_SUFFIX="__ATTRS"
METHODS_SUFFIX="__METHODS"
METHOD_SUFFIX="__METHOD__"

OBJECT_TYPE_ATTRIBUTE_NAME="__type__"
OBJECT_PARENT_ATTRIBUTE_NAME="__parent__"
OBJECT_NAME_ATTRIBUTE_NAME="__name__"

CLASS_TYPE_NAME="class"
INSTANCE_TYPE_NAME="instance"

VALID_OBJECT_NAME_REGEX="^[_[:alnum:]]+$"
VALID_ATTRIBUTE_NAME_REGEX="^[_[:alnum:]]+(\?|\!)?$"
VALID_METHOD_NAME_REGEX="${VALID_ATTRIBUTE_NAME_REGEX}"
PROTECTED_NAME_REGEX="^_[[:alnum:]]+"

INIT_METHOD_NAME="__init__"
DESTROY_METHOD_NAME="__destroy__"