on:
  push:
    branches:
      - main
    paths:
      - 'lib/**'
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple
          package-name: bash_oop